### ISSUE TITLE
Default Loop Times

### ISSUE THREAD

**Issue by git-pi** [Screenly/screenly-ose#119]
The default for new asset display via the web interface is 7 days.  Can we get a check box for "Loop indefinitely" or a dropdown that might give something like "1 day," "1 week," "1 month," "indefinite" and "Date Range" selections?

Again, don't know how to flag this as an enhancement request, sorry...

**Comment by vpetersson** [comment]
Thanks @rusko124!

**Comment by vpetersson** [comment]
This feature breaks when you try to edit an asset.

![localhost_8080_ laptop with hidpi screen](https://user-images.githubusercontent.com/357664/45543548-ae687600-b80c-11e8-95df-b82bd1378540.png)

How to reproduce:

 * Upload an image asset
 * Click edit
 * Select "Play for: Forever"

Traceback:

```
Traceback (most recent call last):
  File "server.py", line 360, in api_view
    return view(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful_swagger_2/swagger.py", line 219, in inner
    return f(self, *args, **kwargs)
  File "server.py", line 749, in put
    asset = prepare_asset_v1_2(request, asset_id)
  File "server.py", line 350, in prepare_asset_v1_2
    asset['end_date'] = date_parser.parse(get('end_date')).replace(tzinfo=None)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 395, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format
```

**Comment by rusko124** [comment]
@vpetersson 
made fixes
