### ISSUE TITLE
Screenly crashing after reload some assets

### ISSUE THREAD

**Issue by viniciosbarros** [Screenly/screenly-ose#1320]
Screenly crashing after reload some assets

#### Overview of the Issue

```
11.03.20 00:30:44 (-0300) <screenly-viewer> get_next_asset after refresh
11.03.20 00:30:44 (-0300) <screenly-viewer> get_next_asset counter 0 returning asset 2 of 5
11.03.20 00:30:44 (-0300) <screenly-viewer> Showing asset IMG_1634.JPG (image)
11.03.20 00:30:44 (-0300) <screenly-viewer> Asset URI /data/screenly_assets/4282cf128c384cdd9b43b8092acf9147
11.03.20 00:30:44 (-0300) <screenly-viewer> Already showing file:///tmp/screenly_html/black_page.html, reloading it.
11.03.20 00:30:44 (-0300) <screenly-viewer> Sleeping for 5
11.03.20 00:30:49 (-0300) <screenly-viewer> Last update: 2020-03-10 23:37:50
11.03.20 00:30:51 (-0300) <screenly-viewer> get_next_asset
11.03.20 00:30:51 (-0300) <screenly-viewer> refresh_playlist
11.03.20 00:30:51 (-0300) <screenly-viewer> refresh: counter: (0) deadline (2020-04-10 03:09:00) timecur (2020-03-11 03:30:51.407322)
11.03.20 00:30:51 (-0300) <screenly-viewer> get_next_asset after refresh
11.03.20 00:30:51 (-0300) <screenly-viewer> get_next_asset counter 0 returning asset 3 of 5
11.03.20 00:30:51 (-0300) <screenly-viewer> Showing asset IMG_1579.JPG (image)
11.03.20 00:30:51 (-0300) <screenly-viewer> Asset URI /data/screenly_assets/0316245f221a4fc2b36529c5d9633461
11.03.20 00:30:51 (-0300) <screenly-viewer> Already showing file:///tmp/screenly_html/black_page.html, reloading it.
11.03.20 00:30:51 (-0300) <screenly-viewer> browser found dead, restarting
11.03.20 00:30:51 (-0300) <screenly-viewer> Loading browser...
11.03.20 00:30:51 (-0300) <screenly-viewer> Viewer crashed.
11.03.20 00:30:51 (-0300) <screenly-viewer> Traceback (most recent call last):
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 580, in <module>
11.03.20 00:30:51 (-0300) <screenly-viewer>     main()
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 575, in main
11.03.20 00:30:51 (-0300) <screenly-viewer>     asset_loop(scheduler)
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 452, in asset_loop
11.03.20 00:30:51 (-0300) <screenly-viewer>     view_image(uri)
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 335, in view_image
11.03.20 00:30:51 (-0300) <screenly-viewer>     cb=lambda b: 'COMMAND_EXECUTED' in b and 'setimg' in b)
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 307, in browser_send
11.03.20 00:30:51 (-0300) <screenly-viewer>     load_browser()
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 262, in load_browser
11.03.20 00:30:51 (-0300) <screenly-viewer>     if browser:
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 334, in __len__
11.03.20 00:30:51 (-0300) <screenly-viewer>     return len(str(self))
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 370, in __str__
11.03.20 00:30:51 (-0300) <screenly-viewer>     else: return unicode(self).encode(self.call_args["encoding"])
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 373, in __unicode__
11.03.20 00:30:51 (-0300) <screenly-viewer>     if self.process and self.stdout:
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 316, in stdout
11.03.20 00:30:51 (-0300) <screenly-viewer>     self.wait()
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 295, in wait
11.03.20 00:30:51 (-0300) <screenly-viewer>     self._handle_exit_code(self.process.wait())
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 309, in _handle_exit_code
11.03.20 00:30:51 (-0300) <screenly-viewer>     self.process.stderr
11.03.20 00:30:51 (-0300) <screenly-viewer> SignalException_9: 
11.03.20 00:30:51 (-0300) <screenly-viewer> 
11.03.20 00:30:51 (-0300) <screenly-viewer>   RAN: '/usr/bin/uzbl-browser --config=- --uri=None --print-events'
11.03.20 00:30:51 (-0300) <screenly-viewer> 
11.03.20 00:30:51 (-0300) <screenly-viewer>   STDOUT:
11.03.20 00:30:51 (-0300) <screenly-viewer> EVENT [49] INSTANCE_START 49
11.03.20 00:30:51 (-0300) <screenly-viewer> EVENT [49] BUILTINS 'back forward scroll reload reload_ign_cache stop zoom_in zoom_out toggle_zoom_type uri js script toggle_status spawn sync_spawn sync_spawn_exec sh sync_sh exit search search_reverse search_clear dehilight set toggle dump_config dump_config_as_events chain print event request menu_add menu_link_add menu_image_add menu_editable_add menu_separator menu_link_separator menu_image_separator menu_editable_separator menu_remove menu_link_remove menu_image_remove menu_editable_remove hardcopy include show_inspector add_cookie delete_cookie clear_cookies download '
11.03.20 00:30:51 (-0300) <screenly-viewer> EVENT [49] VARIABLE_SET status_format str '<b>@[@TITLE]@</b> - @[@uri]@ - <span foreground="#bbb">@NAME</span>'
11.03.20 00:30:51 (-0300) <screenly-viewer> EVENT [49] VARIABLE_SET sh... (6324 more, please see e.stdout)
11.03.20 00:30:51 (-0300) <screenly-viewer> 
11.03.20 00:30:51 (-0300) <screenly-viewer>   STDERR:
11.03.20 00:30:51 (-0300) <screenly-viewer> 
11.03.20 00:30:51 (-0300) <screenly-viewer> Traceback (most recent call last):
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 580, in <module>
11.03.20 00:30:51 (-0300) <screenly-viewer>     main()
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 575, in main
11.03.20 00:30:51 (-0300) <screenly-viewer>     asset_loop(scheduler)
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 452, in asset_loop
11.03.20 00:30:51 (-0300) <screenly-viewer>     view_image(uri)
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 335, in view_image
11.03.20 00:30:51 (-0300) <screenly-viewer>     cb=lambda b: 'COMMAND_EXECUTED' in b and 'setimg' in b)
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 307, in browser_send
11.03.20 00:30:51 (-0300) <screenly-viewer>     load_browser()
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "viewer.py", line 262, in load_browser
11.03.20 00:30:51 (-0300) <screenly-viewer>     if browser:
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 334, in __len__
11.03.20 00:30:51 (-0300) <screenly-viewer>     return len(str(self))
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 370, in __str__
11.03.20 00:30:51 (-0300) <screenly-viewer>     else: return unicode(self).encode(self.call_args["encoding"])
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 373, in __unicode__
11.03.20 00:30:51 (-0300) <screenly-viewer>     if self.process and self.stdout:
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 316, in stdout
11.03.20 00:30:51 (-0300) <screenly-viewer>     self.wait()
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 295, in wait
11.03.20 00:30:51 (-0300) <screenly-viewer>     self._handle_exit_code(self.process.wait())
11.03.20 00:30:51 (-0300) <screenly-viewer>   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 309, in _handle_exit_code
11.03.20 00:30:51 (-0300) <screenly-viewer>     self.process.stderr
11.03.20 00:30:51 (-0300) <screenly-viewer> sh.SignalException_9: 
11.03.20 00:30:51 (-0300) <screenly-viewer> 
11.03.20 00:30:51 (-0300) <screenly-viewer>   RAN: '/usr/bin/uzbl-browser --config=- --uri=None --print-events'
11.03.20 00:30:51 (-0300) <screenly-viewer> 
11.03.20 00:30:51 (-0300) <screenly-viewer>   STDOUT:
11.03.20 00:30:51 (-0300) <screenly-viewer> EVENT [49] INSTANCE_START 49
11.03.20 00:30:51 (-0300) <screenly-viewer> EVENT [49] BUILTINS 'back forward scroll reload reload_ign_cache stop zoom_in zoom_out toggle_zoom_type uri js script toggle_status spawn sync_spawn sync_spawn_exec sh sync_sh exit search search_reverse search_clear dehilight set toggle dump_config dump_config_as_events chain print event request menu_add menu_link_add menu_image_add menu_editable_add menu_separator menu_link_separator menu_image_separator menu_editable_separator menu_remove menu_link_remove menu_image_remove menu_editable_remove hardcopy include show_inspector add_cookie delete_cookie clear_cookies download '
11.03.20 00:30:51 (-0300) <screenly-viewer> EVENT [49] VARIABLE_SET status_format str '<b>@[@TITLE]@</b> - @[@uri]@ - <span foreground="#bbb">@NAME</span>'
11.03.20 00:30:51 (-0300) <screenly-viewer> EVENT [49] VARIABLE_SET sh... (6324 more, please see e.stdout)
11.03.20 00:30:51 (-0300) <screenly-viewer> 
11.03.20 00:30:51 (-0300) <screenly-viewer>   STDERR:
11.03.20 00:30:51 (-0300) <screenly-viewer> 
11.03.20 00:30:55 (-0300) Service exited 'screenly-viewer sha256:d539389a133f3b4623c28766bb6f807e7dbaf6ea8d42749d5d08bc75c20a3749'
11.03.20 00:30:56 (-0300) <screenly-celery> [2020-03-11 03:30:55,992: INFO/Beat] beat: Starting...
```
#### Reproduction Steps

Steps to reproduce this issue

* Using Balena create a new application
* Clone screenly-se project
* Flash sd card
* Build and wait to upload
* Press Add Asset
* Wait for the asset to show up on the screen
* some assets will be shown and Screenly will crash

### Environment

* Raspberry Pi Hardware Version: raspberry pi 3 - 32 bits
* Raspberry Pi Network Setup: Ethernet
* Screenly OSE Version: f2cbd9f

**Comment by ealmonte32** [comment]
@viniciosbarros 
I can confirm I've seen that as well.
Can you confirm which version of the "sh" package you are using?
You can check with typing this from console: `pip freeze | grep sh`
