### ISSUE TITLE
screenly_srly-ose-viewer:latest-pi4 in bootloop

### ISSUE THREAD

**Issue by xlegs** [Screenly/screenly-ose#1553]
#### Overview of the Issue

screenly_srly-ose-viewer:latest-pi4 in bootloop

This prevents Screenly from working completely. 

`docker container ls -a` shows

```
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                          PORTS                      NAMES
4ebe1678ef03        screenly/srly-ose-nginx:latest        "/usr/bin/entry.sh n…"   21 minutes ago      Up 19 minutes                   0.0.0.0:80->80/tcp         screenly_srly-ose-nginx_1
2e3be3c0fa3c        screenly/srly-ose-websocket:latest    "/usr/bin/entry.sh p…"   21 minutes ago      Up 19 minutes                                              screenly_srly-ose-websocket_1
6ddce06bd56a        screenly/srly-ose-viewer:latest-pi4   "/usr/bin/entry.sh b…"   21 minutes ago      Restarting (0) 17 seconds ago                              screenly_srly-ose-viewer_1
ad3cd27bf294        screenly/srly-ose-celery:latest       "/usr/bin/entry.sh /…"   21 minutes ago      Up 19 minutes                                              screenly_srly-ose-celery_1
9808dac1810f        screenly/srly-ose-server:latest       "/usr/bin/entry.sh b…"   21 minutes ago      Up 19 minutes                                              screenly_srly-ose-server_1
34d3fad8fa86        screenly/srly-ose-redis:latest        "/usr/bin/entry.sh r…"   21 minutes ago      Up 19 minutes                   127.0.0.1:6379->6379/tcp   screenly_redis_1
```

`docker container logs screenly_srly-ose-viewer_1` shows

```
Home directory not accessible: Permission denied
[00d59bd8] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
Viewer crashed.
Traceback (most recent call last):
  File "viewer.py", line 464, in <module>
    main()
  File "viewer.py", line 429, in main
    setup()
  File "viewer.py", line 357, in setup
    db_conn = db.conn(settings['database'])
  File "/usr/src/app/lib/db.py", line 5, in <lambda>
    conn = lambda db: sqlite3.connect(db, detect_types=sqlite3.PARSE_DECLTYPES)
OperationalError: unable to open database file
Traceback (most recent call last):
  File "viewer.py", line 464, in <module>
    main()
  File "viewer.py", line 429, in main
    setup()
  File "viewer.py", line 357, in setup
    db_conn = db.conn(settings['database'])
  File "/usr/src/app/lib/db.py", line 5, in <lambda>
    conn = lambda db: sqlite3.connect(db, detect_types=sqlite3.PARSE_DECLTYPES)
sqlite3.OperationalError: unable to open database file
./bin/start_viewer.sh: line 47: kill: (36) - No such process
```

#### Reproduction Steps

* Install development version of Screenly over production on fresh Raspbian

#### Environment
Screenly version: master@e2072ee
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by ealmonte32** [comment]
I would say get raspbian buster lite, do a fresh install..
